## Q.1. Write a function so that the columns of the output matrix are powers of the input
## vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
import numpy as np

In [52]:
def Alexandre_Theophile(vector,number_of_column):
    """
    Docstring(vector,number_of_column)
    returns columns of the output matrix are powers of the input
    vector
    
    parameters:
    ------------
    vector: accept any vector
    number_of_column: accept the number of column should be available for output matrix
    
    """
    #extracting the row and columns of output matrix
    rows,cols=len(vector),number_of_column
    
    #creating a matrix which has element 0. matrix dimension will be defined by above rows and cols
    matrix=np.mat(np.zeros((rows,cols)),dtype=np.int64)
    
    #calculating the number of element present in vector
    no_of_element_of_vector=len(vector)
    
    
    for i in range(cols):
        power=cols-i-1
        #print("power",power)
        for j in range(no_of_element_of_vector):
            #print(vector[j],vector[j]**power)
            
            matrix[j,i]=int(vector[j]**power)
            #print(matrix[j,i])
        #print(matrix)
    return matrix
    

In [54]:
Alexandre_Theophile(vector=[9,7,5,4],number_of_column=5)

matrix([[6561,  729,   81,    9,    1],
        [2401,  343,   49,    7,    1],
        [ 625,  125,   25,    5,    1],
        [ 256,   64,   16,    4,    1]])

# Problem Statement 2: 
</br>

## Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:


### The moving average sequence has n-k+1 elements as shown below.
### The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10

</br>
===== == == == == == == == == == ==

</br>

Input 10 20 30 40 50 60 70 80 90 100

</br>


y1 25 = (10+20+30+40)/4

</br>

y2 35 = (20+30+40+50)/4

</br>

y3 45 = (30+40+50+60)/4

</br>

y4 55 = (40+50+60+70)/4

</br>

y5 65 = (50+60+70+80)/4

</br>

y6 75 = (60+70+80+90)/4

</br>

y7 85 = (70+80+90+100)/4

</br>

### Thus, the moving average sequence has n-k+1=10-4+1=7 values.

## Question: 
### Write a function to find moving average in an array over a window:
#### Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [138]:
input_array=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
#input_array=np.arange(10,110,10)
k=3

In [139]:
input_array

[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

In [140]:
n=len(input_array)

In [141]:
moving_array_sequence_has_value=n-k+1

In [142]:
moving_array_sequence_has_value

11

In [143]:
output_array=np.zeros((moving_array_sequence_has_value,1)).flatten()

In [144]:
output_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [145]:
for i in range(moving_array_sequence_has_value):
    text="("
    for j in range(k):
        text=text+str(input_array[i+j])+'+'
        output_array[i]=output_array[i]+input_array[i+j]
    output_array[i]=output_array[i]/k
    text=text+")"
    print('y'+str(i+1),"{:.2f}".format(output_array[i]),"=",text[0:len(text)-2]+')/'+str(k),end="\n\n")
#print(output_array)

y1 5.00 = (3+5+7)/3

y2 4.67 = (5+7+2)/3

y3 5.67 = (7+2+8)/3

y4 6.67 = (2+8+10)/3

y5 9.67 = (8+10+11)/3

y6 28.67 = (10+11+65)/3

y7 49.33 = (11+65+72)/3

y8 72.67 = (65+72+81)/3

y9 84.00 = (72+81+99)/3

y10 93.33 = (81+99+100)/3

y11 116.33 = (99+100+150)/3



In [146]:
output_array

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])